### ISSUE TITLE
Lua error

### ISSUE THREAD

**Issue by spliffmaster** [BloodDragon2580/MoveAround-for-BfA#1]
First, a huge thank you for this wonderful addon.  I received this error just a minute ago while beginning the invasion quests:

1x [ADDON_ACTION_BLOCKED] AddOn 'MoveAround' tried to call the protected function 'UIParent:SetAttribute()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML\UIParent.lua"]:2994: in function `UpdateUIPanelPositions'
[string "@FrameXML\UIParent.lua"]:2613: in function <FrameXML\UIParent.lua:2602>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML\UIParent.lua"]:3700: in function <FrameXML\UIParent.lua:3698>
[string "=[C]"]: in function `securecall'
[string "@FrameXML\UIParent.lua"]:2889: in function `SetUIPanel'
[string "@FrameXML\UIParent.lua"]:2738: in function `ShowUIPanel'
[string "@FrameXML\UIParent.lua"]:2606: in function <FrameXML\UIParent.lua:2602>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML\UIParent.lua"]:3457: in function `ShowUIPanel'
[string "@FrameXML\GossipFrame.lua"]:80: in function `GossipFrame_HandleShow'
[string "@FrameXML\CustomGossipFrameBase.lua"]:47: in function `HandleOpenEvent'
[string "@FrameXML\CustomGossipFrameBase.lua"]:39: in function <FrameXML\CustomGossipFrameBase.lua:37>

**Comment by BloodDragon2580** [comment]
Unfortunately there is nothing I can do about it. MoveAround tries to call a protected form. And then Blizzard reports the error. The only thing you can do there is a / reload.

**Comment by BloodDragon2580** [comment]
That is a taint not an error.

**Comment by spliffmaster** [comment]
Ah okay thanks for the quick reply.

**Comment by BloodDragon2580** [comment]
No Problem.
