### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Spydawg** [BloodDragon2580/MoveAround-for-BfA#10]
`5x ...aceMoveAround/settings/MoveAroundOptions.lua:337: attempt to call global 'GetAddOnMetadata' (a nil value)
[string "@MoveAround/settings/MoveAroundOptions.lua"]:337: in function `SetupConfig'
[string "@MoveAround/MoveAround.lua"]:537: in function <MoveAround/MoveAround.lua:533>

Locals:
self = <table> {
 waitTable = <table> {
 }
 resetTable = <table> {
 }
}
MoveAroundOptionsTitle = FontString {
}
lockMoveTitle = FontString {
}
yOffset = -230
lockScaleTitle = FontString {
}
frameToggleTitle = FontString {
}
MoveAroundOptionsVersionLabel = FontString {
}
MoveAroundOptionsVersionContent = FontString {
}
(*temporary) = FontString {
}
(*temporary) = nil
(*temporary) = "MoveAround"
(*temporary) = "Version"
(*temporary) = "attempt to call global 'GetAddOnMetadata' (a nil value)"
MoveAroundOptionsPanel = <table> {
 optionspanel = MoveAroundOptionsPanel {
 }
 config = <table> {
 }
}
L = <table> {
 Position for each frame are saved.  = "Position for each frame are saved. "
 Yes = "Yes"
 Bags = "Bags"
 ALT To Drag = " ALT To Drag"
 While frame dragging is locked, a modifier key must be pressed to drag a frame. = " While frame dragging is locked, a modifier key must be pressed to drag a frame."
 /MoveAround - Print allowed commands. = "|cffd6266c/MoveAround|r - Print allowed commands.."
 Whether MoveAround will modify Miscellaneous Frames (example: QuestTracker). = "Whether MoveAround will modify Miscellaneous Frames (example: QuestTracker)."
 Whether MoveAround will modify Buttons (example: Open Ticket Button). = "Whether MoveAround will modify Buttons (example: Open Ticket Button)."
 Lock Frame Dragging = " Lock Frame Dragging"
 Buttons = "Buttons"
 MoveAround: Allowed commands: = "|cffd6266cMoveAround:|r Allowed commands:"
  during combat. = " during combat."
 Reset Frames = "Reset Frames"
 Reset position for all modified frames. = "Reset position for all modified frames."
 /MoveAround reset - Reset position for all modified frames. = "|cffd6266c/MoveAround reset|r - Reset position for all modified frames."
 For additional configuration options, visit  = "For additional configuration options, visit "
 Whether MoveAround will modify Windows (example: Talents). = "Whether MoveAround will modify Windows (example: Talents)."
 /MoveAround version|r - Print addon version. = "/MoveAround version|r - Print addon version."
 Whether ALT can be pressed while frame dragging is locked to drag a frame. = " Whether ALT can be pressed while frame dragging is locked to drag a frame."
 MoveAround: Cannot move  = "|cffFFC125MoveAround:|r Cannot move "
 Whether MoveAround will modify Bags. = "Whether MoveAround will modify Bags."
 Windows = "Windows"
 Whether CTRL can be pressed while frame dragging is locked to drag a frame. = " Whether CTRL can be pressed while frame dragging is locked to drag a frame."
 /MoveAround help - Print help message. = "|cffd6266c/MoveAround help|r - Print help message."
 No = "No"
 SHIFT To Drag = " SHIFT To Drag"
 Right-click and drag up or down to scale a frame. = "Right-click and drag up or down to scale a frame."
 Miscellaneous = "Miscellaneous"
 CTRL To Drag = " CTRL To Drag"
  -> AddOns -> MoveAround. = " -> AddOns -> MoveAround."
 Enabled Frames = "Enabled Frames"
 Are you sure you want to reset position for all modified frames? = "Are you sure you want to reset position for all modified frames?"
 MoveAround: Modifies default UI frames so you can click and drag to move.  = "|cffd6266c/MoveAround:|r Modifies default UI frames so you can click and drag to move. "
 Left-click and drag anywhere to move a frame.  = "Left-click + Shift and drag anywhere to move a frame. "
 MoveAround = "|cffd6266cMoveAround|r"
 Whether SHIFT can be pressed while frame dragging is locked to drag a frame. = " Whether SHIFT can be pressed while frame dragging is locked to drag a frame."
}
isRetail = true
`

**Comment by BloodDragon2580** [comment]
should fixed now:
https://github.com/BloodDragon2580/MoveAround/commit/23750feb8c350040eb999605a50231158d33a0ea
Upload to curse is done

**Comment by Spydawg** [comment]
thanks
