### ISSUE TITLE
Bug with ver 11.0.2 08/20/2024

### ISSUE THREAD

**Issue by FlareStarrr** [BloodDragon2580/MoveAround-for-BfA#11]
25x [string "MoveAround/Libs/TaintLess/..."]:108: hooksecurefunc(): ObjectiveTracker_Update is not a function
[string "=[C]"]: in function `hooksecurefunc'
[string "MoveAround/Libs/TaintLess/TaintLess.xml:<Scripts>"]:108: in main chunk

Locals:

**Comment by FlareStarrr** [comment]
1x AceLocale-3.0-6: MoveAround: Missing entry for 'Right-click and drag up or down to scale a frame. '
[string "@MoveAround/settings/MoveAroundHelpers.lua"]:346: in function `PrintHelp'
[string "@MoveAround/settings/MoveAroundHelpers.lua"]:361: in function `HandleSlashCommands'
[string "@MoveAround/settings/MoveAroundOptions.lua"]:413: in function `?'
[string "@Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5468: in function `ChatEdit_ParseText'
[string "@Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5120: in function `ChatEdit_SendText'
[string "@Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5156: in function <Blizzard_ChatFrameBase/Mainline/ChatFrame.lua:5152>
[string "=[C]"]: in function `ChatEdit_OnEnterPressed'
[string "*ChatFrame.xml:140_OnEnterPressed"]:1: in function <[string "*ChatFrame.xml:140_OnEnterPressed"]:1>

Locals:
self = <table> {
 waitTable = <table> {
 }
 scaleHandlerFrame = ScaleHandlerFrame {
 }
 resetTable = <table> {
 }
}
interfaceOptionsLabel = "Interface"
(*temporary) = "|cffd6266c/MoveAround:|r Modifies default UI frames so you can click and drag to move. "
(*temporary) = "Left-click + Shift and drag anywhere to move a frame. "
(*temporary) = <table> {
 Position for each frame are saved.  = "Position for each frame are saved. "
 Yes = "Yes"
 Bags = "Bags"
 ALT To Drag = " ALT To Drag"
 While frame dragging is locked, a modifier key must be pressed to drag a frame. = " While frame dragging is locked, a modifier key must be pressed to drag a frame."
 /MoveAround - Print allowed commands. = "|cffd6266c/MoveAround|r - Print allowed commands.."
 Whether MoveAround will modify Miscellaneous Frames (example: QuestTracker). = "Whether MoveAround will modify Miscellaneous Frames (example: QuestTracker)."
 Whether MoveAround will modify Buttons (example: Open Ticket Button). = "Whether MoveAround will modify Buttons (example: Open Ticket Button)."
 Lock Frame Dragging = " Lock Frame Dragging"
 Buttons = "Buttons"
 MoveAround: Allowed commands: = "|cffd6266cMoveAround:|r Allowed commands:"
  during combat. = " during combat."
 Reset Frames = "Reset Frames"
 Reset position for all modified frames. = "Reset position for all modified frames."
 /MoveAround reset - Reset position for all modified frames. = "|cffd6266c/MoveAround reset|r - Reset position for all modified frames."
 For additional configuration options, visit  = "For additional configuration options, visit "
 Whether MoveAround will modify Windows (example: Talents). = "Whether MoveAround will modify Windows (example: Talents)."
 /MoveAround version|r - Print addon version. = "/MoveAround version|r - Print addon version."
 Whether ALT can be pressed while frame dragging is locked to drag a frame. = " Whether ALT can be pressed while frame dragging is locked to drag a frame."
 MoveAround: Cannot move  = "|cffFFC125MoveAround:|r Cannot move "
 Whether MoveAround will modify Bags. = "Whether MoveAround will modify Bags."
 Windows = "Windows"
 Whether CTRL can be pressed while frame dragging is locked to drag a frame. = " Whether CTRL can be pressed while frame dragging is locked to drag a frame."
 Right-click and drag up or down to scale a frame.  = "Right-click and drag up or down to scale a frame. "
 /MoveAround help - Print help message. = "|cffd6266c/MoveAround help|r - Print help message."
 No = "No"
 SHIFT To Drag = " SHIFT To Drag"
 Right-click and drag up or down to scale a frame. = "Right-click and drag up or down to scale a frame."
 Miscellaneous = "Miscellaneous"
 CTRL To Drag = " CTRL To Drag"
  -> AddOns -> MoveAround. = " -> AddOns -> MoveAround."
 Enabled Frames = "Enabled Frames"
 Are you sure you want to reset position for all modified frames? = "Are you sure you want to reset position for all modified frames?"
 MoveAround: Modifies default UI frames so you can click and drag to move.  = "|cffd6266c/MoveAround:|r Modifies default UI frames so you can click and drag to move. "
 Left-click and drag anywhere to move a frame.  = "Left-click + Shift and drag anywhere to move a frame. "
 MoveAround = "|cffd6266cMoveAround|r"
 Whether SHIFT can be pressed while frame dragging is locked to drag a frame. = " Whether SHIFT can be pressed while frame dragging is locked to drag a frame."
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
isClassic = false
L = <table> {
 Position for each frame are saved.  = "Position for each frame are saved. "
 Yes = "Yes"
 Bags = "Bags"
 ALT To Drag = " ALT To Drag"
 While frame dragging is locked, a modifier key must be pressed to drag a frame. = " While frame dragging is locked, a modifier key must be pressed to drag a frame."
 /MoveAround - Print allowed commands. = "|cffd6266c/MoveAround|r - Print allowed commands.."
 Whether MoveAround will modify Miscellaneous Frames (example: QuestTracker). = "Whether MoveAround will modify Miscellaneous Frames (example: QuestTracker)."
 Whether MoveAround will modify

**Comment by BloodDragon2580** [comment]
Wil fix it when iam at home. Next 4 houers i think.

**Comment by BloodDragon2580** [comment]
Should now fixed on v8.9 i have uploaded it now on curse.
