### ISSUE TITLE
Lua error

### ISSUE THREAD

**Issue by spliffmaster** [BloodDragon2580/MoveAround-for-BfA#2]
1x CreateFrame: Unknown frame type 'SetUIPanel'
[string "=[C]"]: ?
[string "=[C]"]: in function `CreateFrame'
[string "@MoveAround\Fix\Fix-10034.lua"]:199: in function `InitHooks'
[string "@MoveAround\Fix\Fix-10034.lua"]:211: in main chunk

Locals:
(*temporary) = "SetUIPanel

**Comment by BloodDragon2580** [comment]
Fix is on the way 15 minutes.

**Comment by spliffmaster** [comment]
Thanks!
