### ISSUE TITLE
Conflicts with other addons

### ISSUE THREAD

**Issue by carostad** [BloodDragon2580/MoveAround-for-BfA#6]
Since the release of WoW verison 9.2.5.44325, I have experienced conflicts with Titan Panel, Move Around, and another moving app  MoveAnything. I have deactivated both Move Around and MoveAnything and now Titan loads. Don't know what the issue is but I can use Move and Improve just fine with Titan Panel. Let me know if you figure it out, because I liked this app better.

**Comment by BloodDragon2580** [comment]
I use Titan Panel, Move Around, and MoveAnything +130 other addons without problems. I will check this but i dont think its a Problem by this 3 addons.

**Comment by carostad** [comment]
Okay, just thought I'd pass my issue along I was in touch with the Titan Panel developer first and this is part of our exchange: 

[carostad ](https://sourceforge.net/u/carostad/)- 1 day ago   
Okay, had more energy today to figure this out. It seems to be an incompatibility with addons that move things and Titan. I have both Move Anything and MoveAround installed. After disabling all my addons and reinstalling them one by one, I noticed that Titan would have this error after each of those two were installed. I also have Bartender, but Bartender seems unaffected. I do like being able to move things around. Should I contact those apps as well? I have no idea what happened as there were no updates to any of those three in the past 24 hours that i can see. Did Blizz push out an update that i didn't notice?

 
carostad

[carostad ](https://sourceforge.net/u/carostad/)- 1 day ago   
I ended up finding a different moving addon that seems fine. D4KiR MoveandImprove. I think I've used it in the past so I'm good again. Just curious as to what happened.

 
urnati

[urnati ](https://sourceforge.net/u/urnati/)- 1 day ago  
First, thank you for the investigation effort!
Just glad you found something you liked and is working for you.

Maybe Blizz updated something on the Tue maintenance window?
We do have code to back off when MoveAnything is installed. Had not heard of MoveAround. Nor MoveandImprove.

If you would, please let those authors know you are seeing errors when interacting with Titan. They can reach out to us if we need to make changes to help.
I may install those addons to see if I can reproduce the error.

You may not need a 'move' addon when Dragonflight comes out :).

**Comment by BloodDragon2580** [comment]
I have at the moment no playtime, I start playing with Dragonflight again and can look in to this. But at this time you the only one with problems. Thx anyway for the information my friend.
