### ISSUE TITLE
left & right click dont work after moving a frame

### ISSUE THREAD

**Issue by ToxxicApe** [BloodDragon2580/MoveAround-for-BfA#8]
fresh install, moved one window (group finder). after that both mouse clicks dont work anymore. so i cant move my camera and i cant click on enemys or other stuff.

**Comment by ToxxicApe** [comment]
no lua error btw.

**Comment by BloodDragon2580** [comment]
So I can't see any error. Look at the date on the calendar. It works without any problems. Maybe it's related to another addon? That MoveAround doesn't get along with another addon you're using. 

I have make a little video with timestamp for you so you can see no problems with it.

https://www.youtube.com/watch?v=pvyNp0lhm9o&ab_channel=BloodDragon2580

**Comment by BloodDragon2580** [comment]
Pls use the new version:
https://github.com/BloodDragon2580/MoveAround/releases/tag/MoveAround.v.5.8
