### ISSUE TITLE
Unable to interact with game world after reload/relog

### ISSUE THREAD

**Issue by Lessaj** [BloodDragon2580/MoveAround-for-BfA#9]
In reference to issue #8 I'd like to add some more details around the issue. This specifically occurs either after a /reload or if you log out and back in and only affects interaction with the game world, I can interact with the rest of my UI just fine. Today I enabled every addon one by one until the issue occurred and found disabling this one resolved it. I then started with this addon enabled and enabled the rest one by one until it occurred and found it happens when I enable Shadowed Unit Frames. It was not one the addons I had updated when I first noticed this since this started to happen after DF launch and I was already up to date on every addon and SUF has not been updated since November 16 at the current time. I enabled every other addon one by one to confirm any other conflicts and could not find any.

I rolled MoveAround back one version at a time until the issue was resolved and it does not occur with v5.2, it occurs from v5.4 onwards. v5.2 still appears to work without any issues or conflicts.

**Comment by BloodDragon2580** [comment]
Pls test it with the new version: 
https://github.com/BloodDragon2580/MoveAround/releases/tag/MoveAround.v.5.8

**Comment by Lessaj** [comment]
v5.8 appears to be working fine after reload/relog. Thank you!

**Comment by BloodDragon2580** [comment]
Ok update to Curse is on the way. Thx for testing.
